[package]
name = "conda-share-core"
version = "1.3.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
serde_yaml_bw = "2.5.1"
thiserror = "2.0.17"
